language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=3.0
  - VERSION=2.2
  - VERSION=2.1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="cassandra:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
